### ISSUE TITLE
String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by chatre7** [OpenDBDiff/OpenDBDiff#173] opened 2024-11-06 11:08 UTC
1.  To report an error search first in the Github issues to see if it's already been reported.
2a. If there is no issue, click 'New issue' and paste the error details
    into the body of the issue. To copy the error press "Copy error"
    (At least email the details to opendbdiff@gmail.com)

2b. If the issue exists, but your situation is different please leave a comment with the details.

•   If possible, please attach a SQL script creating the two databases with
    the minimum necessary to reproduce the problem.

Error information
Error Generating Synchronized Script
FormatException: String was not recognized as a valid DateTime.
   at OpenDBDiff.SqlServer.Schema.Model.PartitionFunction.<>c__DisplayClass35_0.<ToSql>b__1(String item) in C:\projects\opendbdiff\OpenDBDiff.SqlServer.Schema\Model\PartitionFunction.cs:line 97   at OpenDBDiff.SqlServer.Schema.Model.PartitionFunction.ToSql() in C:\projects\opendbdiff\OpenDBDiff.SqlServer.Schema\Model\PartitionFunction.cs:line 97
   at OpenDBDiff.SqlServer.Schema.Model.PartitionFunction.ToSqlDiff(ICollection`1 schemas) in C:\projects\opendbdiff\OpenDBDiff.SqlServer.Schema\Model\PartitionFunction.cs:line 189
   at OpenDBDiff.Abstractions.Schema.Model.SchemaList`2.ToSqlDiff(ICollection`1 schemas) in C:\projects\opendbdiff\OpenDBDiff.Abstractions.Schema\Model\SchemaList.cs:line 129
   at OpenDBDiff.SqlServer.Schema.Model.Database.ToSqlDiff(ICollection`1 schemas) in C:\projects\opendbdiff\OpenDBDiff.SqlServer.Schema\Model\Database.cs:line 237
   at OpenDBDiff.UI.MainForm.StartComparison() in C:\projects\opendbdiff\OpenDBDiff\UI\MainForm.cs:line 71

07DA60DA4D5F603C6A86087436DEC991

**Comment by jspraul** [comment] 2024-11-11 03:06
Duplicate of #172. A potential fix is pending; follow progress there.

**Comment by jspraul** [comment] 2024-11-11 03:07
Duplicate of https://github.com/OpenDBDiff/OpenDBDiff/issues/172. A potential fix is pending; follow progress there.

**Closed as not planned by jspraul** 2024-11-11 03:07 UTC

**Comment by ralessirccl** [comment] 2026-03-04 11:03
New user, I still have this error: then? what to do ?
